# Generated by Django 4.1.2 on 2022-11-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="casillas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="operadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroEmpleado", models.CharField(max_length=10)),
                ("numeroDocumento", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="rutas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Pasaporte", "Pasaporte"),
                            ("DNI", "DNI"),
                            ("CIF", "CIF"),
                        ],
                        default="DNI",
                        max_length=30,
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tipoVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mas 6 ejes", "mas 6 ejes"),
                            ("2 ejes", "2 ejes"),
                            ("1 eje", "1 eje"),
                            ("3/4 ejes", "3/4 ejes"),
                            ("3 ejes", "3 ejes"),
                            ("5/6 ejes", "5/6 ejes"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("precio", models.IntegerField()),
                ("descripcion", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="turnos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("dineroInicial", models.IntegerField()),
                (
                    "sentidoCirculacion",
                    models.CharField(
                        choices=[
                            ("sur-norte", "sur-norte"),
                            ("oeste-este", "oeste-este"),
                            ("este-oeste", "este-oeste"),
                            ("norte-sur", "norte-sur"),
                        ],
                        default="este-oeste",
                        max_length=10,
                    ),
                ),
                (
                    "HoraPlanificada",
                    models.CharField(
                        choices=[
                            ("dia", "08:00 - 16:00"),
                            ("madrugada", "00:00 - 08:00 "),
                            ("noche", "16:00 - 00:00"),
                        ],
                        default="00:00 - 08:00",
                        max_length=14,
                    ),
                ),
                (
                    "casilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppPeaje.casillas",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppPeaje.operadores",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importe", models.IntegerField()),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "tipoVehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppPeaje.tipovehiculo",
                    ),
                ),
                (
                    "turno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppPeaje.turnos",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operadores",
            name="tipoDocumento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppPeaje.tipodocumento"
            ),
        ),
        migrations.CreateModel(
            name="estaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("km", models.CharField(max_length=3)),
                ("nombre", models.CharField(max_length=30)),
                (
                    "ruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="AppPeaje.rutas"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="casillas",
            name="estacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppPeaje.estaciones"
            ),
        ),
    ]
