# Generated by Django 4.1.2 on 2022-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("AppPeaje", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[("Pasaporte", "Pasaporte"), ("DNI", "DNI"), ("CIF", "CIF")],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("1 eje", "1 eje"),
                    ("3 ejes", "3 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                    ("2 ejes", "2 ejes"),
                    ("3/4 ejes", "3/4 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="HoraPlanificada",
            field=models.CharField(
                choices=[
                    ("madrugada", "00:00 - 08:00 "),
                    ("dia", "08:00 - 16:00"),
                    ("noche", "16:00 - 00:00"),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("sur-norte", "sur-norte"),
                    ("este-oeste", "este-oeste"),
                    ("oeste-este", "oeste-este"),
                    ("norte-sur", "norte-sur"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
