# Generated by Django 4.1.2 on 2022-11-24 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("AppPeaje", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="operadores",
            old_name="numeroDocumente",
            new_name="numeroDocumento",
        ),
        migrations.RenameField(
            model_name="turnos", old_name="FechaHoraComienzo", new_name="fecha_creacion"
        ),
        migrations.RenameField(
            model_name="turnos", old_name="FechaHoraFin", new_name="fecha_fin"
        ),
        migrations.RemoveField(
            model_name="turnos", name="FechaHoraPlanificadaComienzo"
        ),
        migrations.RemoveField(model_name="turnos", name="FechaHoraPlanificadaFin"),
        migrations.AddField(
            model_name="ticket",
            name="turno",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppPeaje.turnos",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="turnos",
            name="HoraPlanificada",
            field=models.CharField(
                choices=[
                    ("noche", "16:00 - 00:00"),
                    ("dia", "08:00 - 16:00"),
                    ("madrugada", "00:00 - 08:00 "),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="turnos",
            name="operador",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppPeaje.operadores",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[("DNI", "DNI"), ("CIF", "CIF"), ("Pasaporte", "Pasaporte")],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("3 ejes", "3 ejes"),
                    ("3/4 ejes", "3/4 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("2 ejes", "2 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                    ("1 eje", "1 eje"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("este-oeste", "este-oeste"),
                    ("oeste-este", "oeste-este"),
                    ("norte-sur", "norte-sur"),
                    ("sur-norte", "sur-norte"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
