# Generated by Django 4.1.2 on 2022-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("AppPeaje", "0002_alter_tipodocumento_tipo_and_more")]

    operations = [
        migrations.RenameField(
            model_name="operadores",
            old_name="numeroDocumente",
            new_name="numeroDocumento",
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Pasaporte nacional", "DNI"),
                    ("Documento de identidad", "DNI"),
                    ("Internacional", "CIF"),
                ],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("N-S", "norte-sur"),
                    ("O-E)", "oeste-este"),
                    ("E-O", "este-oeste"),
                    ("S-N", "sur-norte"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
