# Generated by Django 4.1.2 on 2022-11-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("AppPeaje", "0004_alter_tipodocumento_tipo_alter_tipovehiculo_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operadores",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[("DNI", "DNI"), ("Pasaporte", "Pasaporte"), ("CIF", "CIF")],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("2 ejes", "2 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                    ("1 eje", "1 eje"),
                    ("3 ejes", "3 ejes"),
                    ("3/4 ejes", "3/4 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="HoraPlanificada",
            field=models.CharField(
                choices=[
                    ("noche", "16:00 - 00:00"),
                    ("dia", "08:00 - 16:00"),
                    ("madrugada", "00:00 - 08:00 "),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("este-oeste", "este-oeste"),
                    ("norte-sur", "norte-sur"),
                    ("oeste-este", "oeste-este"),
                    ("sur-norte", "sur-norte"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
