# Generated by Django 4.1.2 on 2022-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppPeaje", "0006_alter_tipodocumento_tipo_alter_tipovehiculo_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("3 ejes", "3 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("3/4 ejes", "3/4 ejes"),
                    ("1 eje", "1 eje"),
                    ("2 ejes", "2 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="HoraPlanificada",
            field=models.CharField(
                choices=[
                    ("dia", "08:00 - 16:00"),
                    ("madrugada", "00:00 - 08:00 "),
                    ("noche", "16:00 - 00:00"),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="fecha_creacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("este-oeste", "este-oeste"),
                    ("oeste-este", "oeste-este"),
                    ("sur-norte", "sur-norte"),
                    ("norte-sur", "norte-sur"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
