# Generated by Django 4.1.2 on 2022-11-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppPeaje",
            "0007_alter_tipovehiculo_tipo_alter_turnos_horaplanificada_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[("CIF", "CIF"), ("DNI", "DNI"), ("Pasaporte", "Pasaporte")],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("2 ejes", "2 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("3 ejes", "3 ejes"),
                    ("1 eje", "1 eje"),
                    ("3/4 ejes", "3/4 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="fecha_fin",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="operador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="AppPeaje.operadores",
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("sur-norte", "sur-norte"),
                    ("oeste-este", "oeste-este"),
                    ("norte-sur", "norte-sur"),
                    ("este-oeste", "este-oeste"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
