# Generated by Django 4.1.2 on 2022-11-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppPeaje", "0008_alter_tipodocumento_tipo_alter_tipovehiculo_tipo_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Pasaporte nacional", "Pasaporte"),
                    ("Documento de identidad", "DNI"),
                    ("Internacional", "CIF"),
                ],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("5/6 ejes", "Camion 5 ejes"),
                    ("mas 6 ejes", "Camion mas 6 ejes"),
                    ("1 eje", "Motocicleta"),
                    ("3/4 ejes", "Auto con carro"),
                    ("2 ejes", "Auto"),
                    ("3 ejes", "Camion"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("E-O", "este-oeste"),
                    ("N-S", "norte-sur"),
                    ("O-E)", "oeste-este"),
                    ("S-N", "sur-norte"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
