# Generated by Django 4.1.2 on 2022-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppPeaje", "0010_alter_tipodocumento_tipo_alter_tipovehiculo_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[("Pasaporte", "Pasaporte"), ("DNI", "DNI"), ("CIF", "CIF")],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("3/4 ejes < 2.10m", "3/4 ejes < 2.10m"),
                    ("Automoviles", "Automoviles"),
                    ("Motocicletas", "Motocicletas"),
                    ("> 6 ejes", "> 6 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("3/4 ejes > 2.10m", "3/4 ejes > 2.10m"),
                    ("2 ejes", "2 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("sur-norte", "sur-norte"),
                    ("norte-sur", "norte-sur"),
                    ("este-oeste", "este-oeste"),
                    ("oeste-este", "oeste-este"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="quejas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreCompleto", models.CharField(max_length=20)),
                ("gmail", models.EmailField(max_length=254)),
                ("contenidoQueja", models.TextField(max_length=300)),
                ("fechaReclamo", models.DateTimeField(null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppPeaje.ticket",
                    ),
                ),
            ],
        ),
    ]
