# Generated by Django 4.1.2 on 2022-11-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppPeaje",
            "0013_remove_turnos_horacomienzo_alter_tipodocumento_tipo_and_more",
        )
    ]

    operations = [
        migrations.RemoveField(model_name="turnos", name="FechaComienzo"),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("1 eje", "Motocicleta"),
                    ("mas 6 ejes", "Camion mas 6 ejes"),
                    ("2 ejes", "Auto"),
                    ("5/6 ejes", "Camion 5 ejes"),
                    ("3 ejes", "Camion"),
                    ("3/4 ejes", "Auto con carro"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="HoraPlanificadacomienzo",
            field=models.CharField(
                choices=[
                    ("noche", "16:00 - 00:00"),
                    ("madrugada", "00:00 - 08:00 "),
                    ("dia", "08:00 - 16:00"),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("O-E)", "oeste-este"),
                    ("N-S", "norte-sur"),
                    ("S-N", "sur-norte"),
                    ("E-O", "este-oeste"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
