# Generated by Django 4.1.2 on 2022-11-16 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "AppPeaje",
            "0014_remove_turnos_fechacomienzo_alter_tipovehiculo_tipo_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="turnos",
            name="FechaComienzo",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Documento de identidad", "DNI"),
                    ("Internacional", "CIF"),
                    ("Pasaporte nacional", "Pasaporte"),
                ],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("3 ejes", "Camion"),
                    ("1 eje", "Motocicleta"),
                    ("5/6 ejes", "Camion 5 ejes"),
                    ("2 ejes", "Auto"),
                    ("3/4 ejes", "Auto con carro"),
                    ("mas 6 ejes", "Camion mas 6 ejes"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("S-N", "sur-norte"),
                    ("O-E)", "oeste-este"),
                    ("N-S", "norte-sur"),
                    ("E-O", "este-oeste"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
