# Generated by Django 4.1.2 on 2022-11-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppPeaje", "0015_alter_tipodocumento_tipo_alter_tipovehiculo_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casillas",
            name="nombre",
            field=models.CharField(default="casilla", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("CIF", "CIF"),
                    ("Pasaporte", "Pasaporte"),
                    ("Documento de identidad", "DNI"),
                ],
                default="DNI",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tipovehiculo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("2 ejes", "2 ejes"),
                    ("5/6 ejes", "5/6 ejes"),
                    ("3/4 ejes", "3/4 ejes"),
                    ("3 ejes", "3 ejes"),
                    ("mas 6 ejes", "mas 6 ejes"),
                    ("1 eje", "1 eje"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="HoraPlanificadacomienzo",
            field=models.CharField(
                choices=[
                    ("dia", "08:00 - 16:00"),
                    ("madrugada", "00:00 - 08:00 "),
                    ("noche", "16:00 - 00:00"),
                ],
                default="00:00 - 08:00",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="turnos",
            name="sentidoCirculacion",
            field=models.CharField(
                choices=[
                    ("E-O", "este-oeste"),
                    ("O-E)", "oeste-este"),
                    ("S-N", "sur-norte"),
                    ("N-S", "norte-sur"),
                ],
                default="este-oeste",
                max_length=10,
            ),
        ),
    ]
